---
- name: Join manager and worker nodes
  docker_swarm:
    state: join
    advertise_addr: '{{swarm_addr | default(omit)}}'
    remote_addrs: "{{groups['swarm__g_' + swarm_name]}}"
    join_token: "{{hostvars[groups['swarm__g_' + swarm_name][0]].swarm_join_tokens[swarm_node | title]}}"
